### PR TITLE
update LDDs per latest LDDTool

### PR DESCRIPTION
**Pull request by jordanpadams**
LDDTool now uses latest version of inherited dictionaries.

### CODE REVIEW

**Comment by sslavney** [comment]
I see that the M2020 dictionary generated with the latest LDDTool now refers to the latest (I guess) version of the IMG inherited dictionary, PDS4_IMG_1F00_1820. My original issue was that LDDTool appeared to be ignoring the version of the IMG dictionary specified in the M2020 ingest file and substituting an older version. Now it is apparently still ignoring the version specified in the ingest file, and substituting a newer version. I can live with that, if that is the intended behavior, but please document it. I am unable to find the newest LDDTool on GitHub to download and try it for myself; the links from https://nasa-pds.github.io/pds4-information-model/model-lddtool/index.html are returning "not found".

**Comment by jordanpadams** [comment]
@sslavney that is the expected functionality for LDDTool right now. we aren't looking at the schemalocation. if that is something we actually want to happen, we will need to discuss with steve. Personally I prefer that we use whatever version is input to LDDTool. per the github CI/CD works, it is pulling the latest IngestLDD from the IMG repo everytime it regenerates the LDD.

Also, apologies on the broken link. that should be fixed now.

**Comment by jordanpadams** [comment]
also, @sslavney feel free to approve and merge as you see fit.

**Comment by sslavney** [comment]
I downloaded LDDTool 12.0.2 and confirmed that it now uses the latest version of the IMG inherited dictionary when building the M2020 mission dictionary, regardless of which version is specified as input, either inside the ingest file or on the LDDTool command line. The resulting file PDS4_MARS2020_1F00_1000.xsd is now valid, so I'll close that issue too. It would be nice not to have to include the IMG ingest file on the command line, since it is going to be ignored anyway, but I'm happy with this result.

**Pull request merged**
